import os
import sys
import django
import traceback

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'timetable_project.settings')
django.setup()

from core.models import Schedule, ScheduleEntry, ConflictLog
from scheduler.algorithm import generate_schedule

def run():
    try:
        # Clear all previous failed/test schedules, keep only fresh run
        old = Schedule.objects.filter(name__icontains='Autogenerated')
        for s in old:
            ScheduleEntry.objects.filter(schedule=s).delete()
            ConflictLog.objects.filter(schedule=s).delete()
            s.delete()

        schedule = Schedule.objects.create(
            name='M3 Timetable Autogenerated',
            semester='odd',
            year=2           # metadata only; algorithm schedules ALL years
        )
        print(f"Created schedule {schedule.schedule_id}. Starting generation for ALL sections...")
        success, msg = generate_schedule(schedule.schedule_id)
        print(msg)
        if success:
            print(f"\n✓ Done! View at: http://localhost:5173/")
        else:
            print("\n✗ Generation failed. Check logs.")
    except Exception as e:
        with open("err_log.txt", "w", encoding="utf-8") as f:
            traceback.print_exc(file=f)
        print(f"Error: {e}")
        print("Full traceback written to err_log.txt")

if __name__ == '__main__':
    run()
