# Generated by Django 5.1.15 on 2026-01-31 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective')], default='CORE', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='elective_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='lecture_hours',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='practical_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorial_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=3),
        ),
        migrations.CreateModel(
            name='StudentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=50, unique=True)),
                ('program', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('semester_parity', models.CharField(max_length=10)),
                ('section_name', models.CharField(max_length=10)),
                ('student_count', models.IntegerField(default=60)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(max_length=20, unique=True)),
                ('sessions_per_week', models.IntegerField(default=3)),
                ('duration_per_session', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studentsection')),
            ],
        ),
    ]
