# Generated by Django 5.0.1 on 2026-02-08 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(help_text="Model being modified (e.g., 'Teacher')", max_length=50)),
                ('target_id', models.CharField(blank=True, help_text='ID of the object being modified (null for CREATE)', max_length=100, null=True)),
                ('change_type', models.CharField(choices=[('CREATE', 'Create New'), ('UPDATE', 'Update Existing'), ('DELETE', 'Delete')], help_text='Type of change requested', max_length=20)),
                ('proposed_data', models.JSONField(help_text='New or modified data in JSON format')),
                ('current_data', models.JSONField(blank=True, help_text='Current data before change (for UPDATE/DELETE)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('request_notes', models.TextField(blank=True, help_text="HOD's explanation for the change")),
                ('admin_notes', models.TextField(blank=True, help_text="Admin's notes when reviewing")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(help_text='HOD who submitted this request', on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who approved/rejected this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
