# Generated by Django 5.1.15 on 2026-01-31 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_course_type_course_elective_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
