# Generated by Django 5.0.1 on 2026-02-08 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_changerequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='sem',
        ),
    ]
