# Generated by Django 5.0.1 on 2026-02-08 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generatedschedule'),
        ('core', '0004_remove_sem_from_section'),
    ]

    operations = [
    ]
