# Generated by Django 5.0.1 on 2026-02-08 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20260209_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Linked teacher record for faculty/HOD users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='core.teacher'),
        ),
        migrations.DeleteModel(
            name='GeneratedSchedule',
        ),
    ]
