# Generated by Django 5.0.1 on 2026-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_teacher_delete_generatedschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('GENERATE', 'Generated Schedule'), ('BACKUP', 'Backup Created'), ('RESTORE', 'Database Restored')], max_length=20),
        ),
    ]
