# Generated by Django 5.0.1 on 2026-02-12 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_auditlog_user_auditlog_user_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="elective_group",
            field=models.CharField(
                blank=True,
                help_text="Links child courses to parent buckets (e.g., 'PE_SEM5')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_schedulable",
            field=models.BooleanField(
                default=True,
                help_text="True for Core courses and Generic Buckets (PE/FREE). False for specific elective topics.",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.room",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleentry",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.teacher",
            ),
        ),
        migrations.CreateModel(
            name="ElectiveAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.course"
                    ),
                ),
                (
                    "parent_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expansions",
                        to="core.scheduleentry",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.room"
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_assignments",
                        to="core.schedule",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.section"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teacher"
                    ),
                ),
                (
                    "timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.timeslot"
                    ),
                ),
            ],
            options={
                "db_table": "elective_assignments",
            },
        ),
        migrations.CreateModel(
            name="ElectiveAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_group",
                    models.CharField(help_text="A, B, or 'Global'", max_length=10),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="core.course",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.teacher"
                    ),
                ),
            ],
            options={
                "db_table": "elective_allocations",
                "unique_together": {("course", "section_group")},
            },
        ),
    ]
