# Generated by Django 5.0.1 on 2026-03-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_auditlog_user_auditlog_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleentry',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Tracks last modification for optimistic concurrency control'),
        ),
    ]
