# Generated by Django 5.0.1 on 2026-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_schedule_status_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='published_snapshot',
            field=models.JSONField(blank=True, help_text='Snapshot of the schedule layout when it was published. Used to detect changes even if underlying entries are deleted.', null=True),
        ),
    ]
