# Generated by Django 5.0.1 on 2026-03-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_schedule_published_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
