# Generated by Django 5.0.1 on 2026-03-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_user_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="elective_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="is_project",
            field=models.BooleanField(default=False),
        ),
    ]
