# Generated by Django 5.0.1 on 2026-03-06 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_course_elective_type_course_is_project"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachercoursemapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="teachercoursemapping",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_mappings",
                to="core.section",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachercoursemapping",
            unique_together={("teacher", "course", "section")},
        ),
    ]
