# Generated by Django 5.0.1 on 2026-03-06 20:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_teachercoursemapping_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduleentry",
            unique_together={("schedule", "section", "timeslot")},
        ),
        migrations.AlterUniqueTogether(
            name="teachercoursemapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="scheduleentry",
            name="constraint_reason",
            field=models.CharField(
                blank=True,
                help_text="Short explanation of why the AI placed this class here (for Explainability Tooltips)",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teachercoursemapping",
            name="domain_id",
            field=models.IntegerField(
                blank=True,
                help_text="Domain number from mappingop/mappingep (e.g. 1=Cyber Security)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teachercoursemapping",
            name="domain_name",
            field=models.CharField(
                blank=True,
                help_text="Domain name (e.g. 'Cyber Security', 'Data Science')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="teachercoursemapping",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teachercoursemapping",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_mappings",
                to="core.section",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="slot_number",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachercoursemapping",
            unique_together={("teacher", "course", "section", "year")},
        ),
    ]
