# Generated by Django 5.0.1 on 2026-03-06 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_scheduleentry_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="capacity",
            field=models.IntegerField(
                blank=True,
                default=60,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.CreateModel(
            name="WalkingTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_block", models.CharField(max_length=10)),
                ("target_block", models.CharField(max_length=10)),
                (
                    "minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
            ],
            options={
                "db_table": "walking_times",
                "unique_together": {("source_block", "target_block")},
            },
        ),
    ]
