# Generated by Django 5.0.1 on 2026-03-08 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_room_capacity_walkingtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="teachercoursemapping",
            name="preference_level",
            field=models.IntegerField(
                default=3,
                help_text="1=Highest Priority, 5=Lowest Priority (Default=3)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
